version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hexocean_project
      - POSTGRES_USER=hexocean_user
      - POSTGRES_PASSWORD=hexocean_user_pass
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/var/www/hexoceantest/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=hexocean_project
      - POSTGRES_USER=hexocean_user
      - POSTGRES_PASSWORD=hexocean_user_pass
    depends_on:
      - db
  cache:
    image: memcached
    ports:
      - "11211:11211"
volumes:
    pgdata: